version: '3.3'
services:
   fast:
     build:
       dockerfile: Dockerfile
       context: .
     container_name: fast-app
     working_dir: /app
     volumes:
       - ./:/app
     ports:
       - 81:81